image: python:3.10

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - python manage.py collectstatic --noinput
    - python manage.py migrate
    - gunicorn blog_project.wsgi:application
  only:
    - master